name: DevOps Pipeline running inside a Docker Container

trigger:
- main

stages:
- stage: build

  pool:
   name: linux-containers-aks
   # vmImage: ubuntu-latest

  jobs:
 
  - job: buildApp01
    steps:
    - script: |
        echo "Hello from inside Docker Container: $HOSTNAME"
        printenv

  - job: buildApp02
    steps:
    - script: |
        echo "Hello from inside Docker Container: $HOSTNAME"
        printenv
