apiVersion: v1
kind: Secret
metadata:
  name: pipeline-auth
data:
  AZP_URL: aHR0cHM6Ly9kZXYuYXp1cmUuY29tL2hvdXNzZW1kZWxsYWk= # https://dev.azure.com/houssemdellai
  AZP_POOL: bGludXgtY29udGFpbmVycy1ha3M= # linux-containers-aks
  AZP_TOKEN: YXpwZmY0bGp4eXE0cnd3ZzJyaTc0cW1sbjR5eDI1ZzdhbG5yM2ZvbHl3aTNkbmJpcXJ2YQ== # azpff4ljxyq4rwwg2ri74qmln4yx25g7alnr3folywi3dnbiqrva
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azdevops-deployment
  namespace: devopsagent
  labels:
    app: azdevops-agent
spec:
  replicas: 2 #here is the configuration for the actual agent always running
  selector:
    matchLabels:
      app: azdevops-agent
  template:
    metadata:
      labels:
        app: azdevops-agent
    spec:
      containers:
      - name: azdevops-agent
        image: acrforakscluster.azurecr.io/dockeragent:ubuntu-18.04
        env:
          - name: AZP_URL
            valueFrom:
              secretKeyRef:
                name: azdevops
                key: AZP_URL
          - name: AZP_TOKEN
            valueFrom:
              secretKeyRef:
                name: azdevops
                key: AZP_TOKEN
          - name: AZP_POOL
            valueFrom:
              secretKeyRef:
                name: azdevops
                key: AZP_POOL
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-volume
      volumes:
      - name: docker-volume
        hostPath:
          path: /var/run/docker.sock